variables:
  colors:
    primaryColor1: 3A3A3A
    primaryColor2: 5A5A5A
    primaryColor3: CCCCCC
    primaryColor4: 1A1A1A
    primaryColor5: 9A9A9A
    mainMenuBgColor: 9A9A9A
    mainMenuFontColor: 1A1A1A
    mainMenuBorderColor: 1A1A1A
    buttonBgColor: 9A9A9A
    buttonFontColor: 1A1A1A
    buttonBorderColor: 1A1A1A
  fonts:
    defaultHeaderFont: comicSans
    defaultBodyFont: comicSans
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://1.jpg'
favicon:
  use_default: false
  path: 'public://3.jpg'
  mimetype: image/jpeg
omega_toggle_intro: 1
enable_backups: 0
force_subtheme_creation: 0
block_demo_mode: 1
screen_demo_indicator: 1
default_layout: primary
home_layout: front
enable_omegags_layout: 1
layouts: {  }
breakpoint_group_primary: d_theme.default
breakpoint_group_front: d_theme.default
edit_this_layout: front
node_type_article_layout: primary
node_type_page_layout: primary
taxonomy_tags_layout: primary
_core:
  default_config_hash: 1npcySVDyKI-wIits0mjDB9hrmVthB5bNOeMn_LVP2k
compile_scss: 1
show_compile_warning: 1
enable_omega_badge: 1
styles:
  d_theme/d_theme: 1
  omega/omega: 1
  omega/omega_html_elements: 1
  omega/omega_branding: 1
  omega/omega_breadcrumbs: 1
  omega/omega_main_menus: 1
  omega/omega_messages: 1
  omega/omega_pagers: 1
  omega/omega_tabs: 1
  omega/omega_taxonomy_terms: 1
  omega/omega_forms: 1
  omega_starterkit/omega_starterkit: 1
